# Generated by Django 4.2 on 2023-06-02 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toko", "0008_alter_alamatpengiriman_options_payment_order_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="produkitem",
            name="merk",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="produkitem",
            name="min_pesan",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="produkitem",
            name="kategori",
            field=models.CharField(
                choices=[
                    ("AT", "Atasan"),
                    ("AK", "Aksesoris"),
                    ("BA", "Bawahan"),
                    ("SE", "Sepatu"),
                ],
                max_length=2,
            ),
        ),
    ]
