# Generated by Django 4.2 on 2023-06-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toko", "0009_produkitem_merk_produkitem_min_pesan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produkitem",
            name="informasi_produk",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="produkitem",
            name="merk",
            field=models.CharField(null=True),
        ),
    ]
