# Generated by Django 4.2 on 2023-06-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toko", "0011_alter_produkitem_informasi_produk"),
    ]

    operations = [
        migrations.AddField(
            model_name="produkitem",
            name="gambar_dua",
            field=models.ImageField(
                default="default_image.jpeg", null=True, upload_to="product_pics"
            ),
        ),
        migrations.AddField(
            model_name="produkitem",
            name="gambar_satu",
            field=models.ImageField(
                default="default_image.jpeg", null=True, upload_to="product_pics"
            ),
        ),
    ]
