# Generated by Django 4.2 on 2023-06-05 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toko", "0012_produkitem_gambar_dua_produkitem_gambar_satu"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produkitem",
            name="gambar_dua",
            field=models.ImageField(
                default="product_pics/default_image.jpeg",
                null=True,
                upload_to="product_pics",
            ),
        ),
        migrations.AlterField(
            model_name="produkitem",
            name="gambar_satu",
            field=models.ImageField(
                default="product_pics/default_image.jpeg",
                null=True,
                upload_to="product_pics",
            ),
        ),
    ]
