# Generated by Django 4.2 on 2023-06-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("toko", "0013_alter_produkitem_gambar_dua_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produkitem",
            name="warna",
            field=models.CharField(null=True),
        ),
    ]
