# Generated by Django 4.2 on 2023-06-07 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("toko", "0014_produkitem_warna"),
    ]

    operations = [
        migrations.RenameField(
            model_name="produkitem",
            old_name="warna",
            new_name="ukuran",
        ),
    ]
